### ISSUE TITLE
Atenna reference link not working

### ISSUE THREAD

**Issue by mbalestrini** [mattvenn/zero-to-asic-www#10]
This links doesn't seem to be working

https://github.com/mattvenn/zero-to-asic-www/blob/18f75c71e3686d72bf603f9457a0a6c6badbc98a/content/terminology/antenna-report.md?plain=1#L52

**Comment by mattvenn** [comment]
it would be cool to have an 'open an issue about this page' link on the website

**Comment by mattvenn** [comment]
looks like that web page copied this pdf: https://www.ispd.cc/contests/18/lefdefref.pdf

**Comment by mattvenn** [comment]
fixed on main
