### ISSUE TITLE
Missing pdf file - Terminology -> Synthesis

### ISSUE THREAD

**Issue by Zufallsgenerat0r** [mattvenn/zero-to-asic-www#50]
In this line https://github.com/mattvenn/zero-to-asic-www/blob/main/content/terminology/synthesis.md?plain=1#L32 in the Terminology -> Synthesis page the link to the yosys show white paper is not working:
![{65AFC6FD-1CDE-4292-BFE7-4992AA85A0C9}](https://github.com/user-attachments/assets/7458bdd7-4e72-4083-869f-a44945df4d45)

**Comment by mattvenn** [comment]
fixed, thanks!
